AWSTemplateFormatVersion: 2010-09-09
Description: >-
  points
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  ####
  #
  # Lambdas
  #
  ####
  NewBlocksTopic:
    Type: AWS::SNS::Topic

  WalletUpdatesTopic:
    Type: AWS::SNS::Topic

  WalletTracker:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that listens to new blocks, and stores a new record if user doesn't exist
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      CodeUri: backend/functions/
      Handler: wallet-tracker.track
      Events:
        SNSTopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref NewBlocksTopic
      MemorySize: 128
      Timeout: 25
      Policies:
        - AWSLambdaBasicExecutionRole
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - wallet-tracker.ts

  LeaderboardUpdater:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that updates the leaderboard table.
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      CodeUri: backend/functions/
      Handler: leaderboard.calculate
      Events:
        SNSTopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref WalletUpdatesTopic
      MemorySize: 128
      Timeout: 25
      Policies:
        - AWSLambdaBasicExecutionRole
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - leaderboard.ts
