
[project]
name = "StackingDAO"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

# ------------------------------
# Mocks
# ------------------------------

[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[[project.requirements]]
contract_id = "SP2KAF9RF86PVX3NEE27DFV1CQX0T4WGR41X3S45C.commission-trait"

[[project.requirements]]
contract_id = "SP3C0TCQS0C0YY8E0V3EJ7V4X9571885D44M8EFWF.arkadiko-automation-trait-v1"

# ------------------------------
# Protocol
# ------------------------------

[contracts.tax-token-trait-v1]
path = "contracts/tax-token-trait-v1.clar"
clarity_version = 2
epoch = 2.4

[contracts.reserve-trait-v1]
path = "contracts/reserve-trait-v1.clar"
clarity_version = 2
epoch = 2.4

[contracts.commission-trait-v1]
path = "contracts/commission-trait-v1.clar"
clarity_version = 2
epoch = 2.4

[contracts.staking-trait-v1]
path = "contracts/staking-trait-v1.clar"
clarity_version = 2
epoch = 2.4

[contracts.ststx-withdraw-nft]
path = "contracts/ststx-withdraw-nft.clar"
clarity_version = 2
epoch = 2.4

[contracts.ststx-token]
path = "contracts/ststx-token.clar"
clarity_version = 2
epoch = 2.4

[contracts.stdao-token]
path = "contracts/stdao-token.clar"
clarity_version = 2
epoch = 2.4

[contracts.reserve-v1]
path = "contracts/reserve-v1.clar"
clarity_version = 2
epoch = 2.4

[contracts.core-v1]
path = "contracts/core-v1.clar"
clarity_version = 2
epoch = 2.4

[contracts.tax-v1]
path = "contracts/tax-v1.clar"
clarity_version = 2
epoch = 2.4

[contracts.commission-v1]
path = "contracts/commission-v1.clar"
clarity_version = 2
epoch = 2.4

[contracts.stacker-1]
path = "contracts/stacker-1.clar"
clarity_version = 2
epoch = 2.4

[contracts.stacker-2]
path = "contracts/stacker-2.clar"
clarity_version = 2
epoch = 2.4

[contracts.stacker-3]
path = "contracts/stacker-3.clar"
clarity_version = 2
epoch = 2.4

[contracts.stacker-4]
path = "contracts/stacker-4.clar"
clarity_version = 2
epoch = 2.4

[contracts.stacker-5]
path = "contracts/stacker-5.clar"
clarity_version = 2
epoch = 2.4

[contracts.stacker-6]
path = "contracts/stacker-6.clar"
clarity_version = 2
epoch = 2.4

[contracts.stacker-7]
path = "contracts/stacker-7.clar"
clarity_version = 2
epoch = 2.4

[contracts.stacker-8]
path = "contracts/stacker-8.clar"
clarity_version = 2
epoch = 2.4

[contracts.stacker-9]
path = "contracts/stacker-9.clar"
clarity_version = 2
epoch = 2.4

[contracts.stacker-10]
path = "contracts/stacker-10.clar"
clarity_version = 2
epoch = 2.4

[contracts.dao]
path = "contracts/dao.clar"
clarity_version = 2
epoch = 2.4

[contracts.strategy-v0]
path = "contracts/strategy-v0.clar"
clarity_version = 2
epoch = 2.4

[contracts.strategy-v1]
path = "contracts/strategy-v1.clar"
clarity_version = 2
epoch = 2.4

[contracts.staking-v1]
path = "contracts/staking-v1.clar"
clarity_version = 2
epoch = 2.4

# ------------------------------
# Tests
# ------------------------------

[contracts.governance-v0]
path = "contracts/tests/governance-v0.clar"
clarity_version = 2
epoch = 2.4

[contracts.pox-3-mock]
path = "contracts/tests/pox-3-mock.clar"
clarity_version = 2
epoch = 2.4

[contracts.fake-reserve]
path = "contracts/tests/fake-reserve.clar"
clarity_version = 2
epoch = 2.4

[contracts.marketplace-commission]
path = "contracts/tests/marketplace-commission.clar"
clarity_version = 2
epoch = 2.4



[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
