name: CI
on: [push]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: "web"
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: "web"
